language: d

d:
  - dmd
  - ldc

script:
  - dub test :chat --compiler=$DC
  - dub test :format --compiler=$DC
  - dub test :raknet --compiler=$DC
  - dub test :stream --compiler=$DC
  - dub test :terminal --compiler=$DC
